apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ictazurekc-ce51"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ictazurekc-ce51"
  template:
    metadata:
      labels:
        app: "ictazurekc-ce51"
    spec:
      containers:
        - name: "ictazurekc-ce51"
          image: "ictazurepractice.azurecr.io/ictazurekc"
          ports:
          - containerPort: 80