on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ictazurepractice.azurecr.io
        username: ${{ secrets.acr_ictazurepractice_username }}
        password: ${{ secrets.acr_ictazurepractice_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ictazurepractice.azurecr.io/ictazurekc:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ictazurepractice.azurecr.io/ictazurekc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ictazurekc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep orderitem | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace orderitem`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: orderitem
        container-registry-url: ictazurepractice.azurecr.io
        container-registry-username: ${{ secrets.acr_ictazurepractice_username }}
        container-registry-password: ${{ secrets.acr_ictazurepractice_password }}
        secret-name: ictazurekcdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: orderitem
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          ictazurepractice.azurecr.io/ictazurekc:${{ github.sha }}
        imagepullsecrets: |
          ictazurekcdockerauth
